# Generated by Django 4.0.6 on 2022-08-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['author__name', '-pub_year', 'title']},
        ),
    ]
