# Generated by Django 4.0.6 on 2022-08-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='skip_puzzle',
            field=models.BooleanField(default=False),
        ),
    ]
