# Generated by Django 4.0.6 on 2022-08-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_skip_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='alternate_titles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='coauthors',
            field=models.ManyToManyField(blank=True, related_name='coauthored', to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored', to='books.author'),
        ),
    ]
