# Generated by Django 4.0.6 on 2022-08-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options'),
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='book',
            field=models.ForeignKey(limit_choices_to={'opening__iregex': '(\\S+.*(\\n|$)){6}'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='books.book'),
        ),
    ]
